import {
    UIIntentSchema,
    BackendRequirements,
    PromptOptimizerPayload,
    MissingDependency,
} from '../types';
import { optimizePrompt } from './apiClient';

/**
 * Generate a detailed, prescriptive prompt for external AI tools (Cursor, Windsurf, Copilot).
 * The output should be copy-paste ready and actionable.
 */
export async function generateBackendPrompt(
    payload: PromptOptimizerPayload
): Promise<string> {
    try {
        const response = await optimizePrompt(payload);
        if (response) {
            return formatOutputPrompt(response, payload);
        }
    } catch (error) {
        console.error('Prompt generation failed:', error);
    }
    return generateFallbackPrompt(payload);
}

/**
 * Generate a quick prompt without AI for simple cases.
 */
export function generateQuickPrompt(
    uiSchema: UIIntentSchema,
    requirements: BackendRequirements,
    missing: MissingDependency[],
    preferredStack: string = 'supabase'
): string {
    const lines: string[] = [
        `# Backend Implementation for ${uiSchema.component}`,
        '',
        `> Stack: ${preferredStack.toUpperCase()}`,
        '',
        '## What needs to be created:',
        '',
    ];

    // Missing tables
    const missingTables = missing.filter((m) => m.type === 'table');
    if (missingTables.length > 0) {
        lines.push('### Database Tables');
        for (const table of missingTables) {
            const tableReq = requirements.tables.find((t) => table.id.includes(t.name));
            if (tableReq) {
                lines.push(`\n#### \`${tableReq.name}\``);
                lines.push('```sql');
                lines.push(`CREATE TABLE ${tableReq.name} (`);
                lines.push('  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),');
                for (const col of tableReq.columns) {
                    if (col.name !== 'id') {
                        const constraints = col.constraints?.join(' ') || '';
                        lines.push(`  ${col.name} ${col.type.toUpperCase()} ${constraints},`.replace(/,\s*$/, ','));
                    }
                }
                lines.push('  created_at TIMESTAMPTZ DEFAULT NOW()');
                lines.push(');');
                lines.push('```');
            }
        }
    }

    // Missing endpoints
    const missingEndpoints = missing.filter((m) => m.type === 'endpoint');
    if (missingEndpoints.length > 0) {
        lines.push('\n### API Endpoints');
        for (const endpoint of requirements.endpoints) {
            lines.push(`- \`${endpoint.method} ${endpoint.path}\`: ${endpoint.description || 'Handle request'}`);
        }
    }

    // Missing services
    const missingServices = missing.filter((m) => m.type === 'service' || m.type === 'auth');
    if (missingServices.length > 0) {
        lines.push('\n### Services to Configure');
        for (const service of missingServices) {
            lines.push(`- **${service.name}** (${service.type}): ${service.description}`);
        }
    }

    // Instructions
    lines.push('\n---');
    lines.push('\n## Instructions for AI Assistant');
    lines.push('');
    lines.push(`1. Create the database schema in Supabase migrations`);
    lines.push(`2. Set up RLS (Row Level Security) policies`);
    lines.push(`3. Create Edge Functions or API routes for each endpoint`);
    lines.push(`4. Configure required services (${missingServices.map((s) => s.name).join(', ')})`);
    lines.push(`5. Update the frontend component to call these endpoints`);

    return lines.join('\n');
}

function formatOutputPrompt(aiResponse: string, payload: PromptOptimizerPayload): string {
    return `# 🚀 Backend Prompt for ${payload.uiIntentSchema.component}

> Generated by Code Palantir | Stack: ${payload.preferredStack || 'Supabase'}

---

${aiResponse}

---

*Copy this entire prompt to Cursor, Windsurf, or your preferred AI coding assistant.*`;
}

function generateFallbackPrompt(payload: PromptOptimizerPayload): string {
    return `# Backend Implementation for ${payload.uiIntentSchema.component}

## User Intent
"${payload.userIntent}"

## Required Infrastructure

### Tables
${payload.backendRequirements.tables.map((t) => `- ${t.name}`).join('\n') || '- None specified'}

### Endpoints
${payload.backendRequirements.endpoints.map((e) => `- ${e.method} ${e.path}`).join('\n') || '- None specified'}

### Services
${payload.backendRequirements.services.map((s) => `- ${s.name} (${s.type})`).join('\n') || '- None specified'}

## Instructions
Please implement the backend infrastructure listed above using ${payload.preferredStack || 'Supabase'}.
Include proper error handling, validation, and type safety.`;
}
